name: xGameSelector
version: '${version}'
main: cz.fillexe.xgameselector.xGameSelector
api-version: 1.19
commands:
  xgameselector:
    description: xGameSelector plugin command
    usage: '/xgameselector create <sign_name>'
    permission: 'xgameselector.command'
    permission-message: 'You do not have permission to use this command'
    executor: cz.fillexe.xgameselector.function.Commands
